SHELL = /bin/bash -e

TEST_TARGETS := test-yamllint test-cfnvalidate

.PHONY: test $(TEST_TARGETS)

all-test: $(TEST_TARGETS)

# test-cfnvalidate:
# 	@echo "--- Validate Cloudformation"
# 	./scripts/cfn_validate.sh
#
# test-yamllint:
# 	@echo "--- Test Lint YAML"
# 	yamllint -s templates/

env-vars:
ifndef ENVIRONMENT
	$(error ENVIRONMENT is undefined)
endif
