SHELL := /bin/bash -e

DEPLOY_TARGETS := create-cert

.PHONY: env-vars $(DEPLOY_TARGETS)

all-deploy: $(DEPLOY_TARGETS)

create-cert: env-vars
	@echo "--- Create $(ENVIRONMENT) self signed cert"
	openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj '/CN=localhost'; \
	aws acm import-certificate --certificate file://cert.pem --private-key file://key.pem

env-vars:
ifndef ENVIRONMENT
	$(error ENVIRONMENT is undefined)
endif
