---
AWSTemplateFormatVersion: 2010-09-09
Description: "EKS: VPC Stack"

Parameters:
  IAMStack:
    Type: String
    Description: Name of IAM Stack
  VPCStack:
    Type: String
    Description: Name of VPC Stack

Resources:
  Cluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: "dev"
      Version: "1.10"
      RoleArn:
        Fn::ImportValue: !Sub ${IAMStack}::EKSRole
      ResourcesVpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${VPCStack}::ControlPlaneSecurityGroup
        SubnetIds:
          - Fn::ImportValue: !Sub ${VPCStack}::PublicSubnet01
          - Fn::ImportValue: !Sub ${VPCStack}::PublicSubnet02
          - Fn::ImportValue: !Sub ${VPCStack}::PublicSubnet03


Outputs:
  ClusterName:
    Value: !Ref Cluster
    Export:
      Name: !Sub ${AWS::StackName}::ClusterName

  Cluster:
    Value: !GetAtt Cluster.Arn
    Export:
      Name: !Sub ${AWS::StackName}::ClusterArn
