---
AWSTemplateFormatVersion: 2010-09-09
Description: "EKS: IAM Stack"

Resources:
  EKSRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: eks.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy

Outputs:

  EKSRole:
    Value: !GetAtt EKSRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}::EKSRole
