---
- hosts: "localhost"
  vars_files:
    - "../config/{{ lookup('env','ENVIRONMENT') }}/common.yaml"
  tasks:
    - name: EKS Worker Cloudformation Stack
      cloudformation:
        stack_name: "{{ lookup('env','EKS_WORKER_STACK_NAME') }}"
        state: "{{ lookup('env','CFN_STATE') or 'present' }}"
        region: "{{ lookup('env','AWS_DEFAULT_REGION') or 'us-west-2' }}"
        disable_rollback: true
        template: "../templates/eks-worker.yaml"
        template_parameters:
          VPCStack: "{{ lookup('env','VPC_STACK_NAME') }}"
          ClusterStack: "{{ lookup('env', 'EKS_STACK_NAME') }}"
          KeyName: "{{ KeyName }}"
          NodeImageId: "{{ AmiId }}"
          NodeGroupName: "{{ NodeGroupName }}"
        tags:
          Stack: "{{ lookup('env','EKS_WORKER_STACK_NAME') }}"
          KeyPair: "{{ KeyName }}"
          CostCentre: "Cloud Services"
          AmiId: "{{ AmiId }}"
      register: logs

    - debug:
        var: logs
