---
- hosts: "localhost"
  vars_files:
    - "../config/{{ lookup('env','ENVIRONMENT') }}/common.yaml"
  tasks:
    - name: EKS IAM Cloudformation Stack
      cloudformation:
        stack_name: "{{ IAMStack }}"
        state: "{{ State }}"
        region: "{{ Region }}"
        disable_rollback: true
        template: "../templates/eks-iam.yaml"
        tags:
          Stack: "{{ IAMStack }}"
          CostCentre: "Cloud Services"
      register: logs

    - debug:
        var: logs
