---
- hosts: "localhost"
  vars_files:
    - "../config/{{ lookup('env','ENVIRONMENT') }}/common.yaml"
  tasks:
    - name: EKS Cluster Cloudformation Stack
      cloudformation:
        stack_name: "{{ EKSClusterStack }}"
        state: "{{ State }}"
        region: "{{ Region }}"
        disable_rollback: false
        template: "../templates/eks-cluster.yaml"
        template_parameters:
          IAMStack: "{{ IAMStack }}"
          VPCStack: "{{ VPCStack }}"
        tags:
          Stack: "{{ EKSClusterStack }}"
          CostCentre: "Cloud Services"
      async: 3600
      poll: 30
      register: logs

    - debug:
        var: logs
