---
- hosts: "localhost"
  vars_files:
    - "../config/{{ lookup('env','ENVIRONMENT') }}/common.yaml"
  tasks:
    - name: EKS VPC Cloudformation Stack
      cloudformation:
        stack_name: "{{ VPCStack }}"
        state: "{{ State }}"
        region: "{{ Region }}"
        disable_rollback: true
        template: "../templates/amazon-eks-vpc-sample.yaml"
        tags:
          Stack: "{{ VPCStack }}"
          CostCentre: "Cloud Services"
          Test: "{{ AmiId }}"
      register: logs

    - debug:
        var: logs
