---
- hosts: "localhost"
  vars_files:
    - "../config/{{ lookup('env','ENVIRONMENT') }}/common.yaml"
  tasks:
    - name: EKS Worker Cloudformation Stack
      cloudformation:
        stack_name: "{{ WorkerStack }}"
        state: "{{ State }}"
        region: "{{ Region }}"
        disable_rollback: true
        template: "../templates/eks-worker.yaml"
        template_parameters:
          VPCStack: "{{ VPCStack }}"
          ClusterStack: "{{ EKSClusterStack }}"
          KeyName: "{{ KeyName }}"
          NodeImageId: "{{ AmiId }}"
          NodeGroupName: "{{ NodeGroupName }}"
        tags:
          Stack: "{{ WorkerStack }}"
          KeyPair: "{{ KeyName }}"
          CostCentre: "Cloud Services"
          AmiId: "{{ AmiId }}"
      register: logs

    - debug:
        var: logs
